name: Lint Python code with flake8

on:
  pull_request:
    branches: [ main ]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  # Install flake8

    - name: Run flake8
      run: flake8 .